# Generated by Django 4.0.3 on 2022-03-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Код судна')),
                ('name', models.CharField(max_length=255, verbose_name='Имя судна')),
            ],
            options={
                'verbose_name': 'Судно',
                'verbose_name_plural': 'Судна',
            },
        ),
        migrations.CreateModel(
            name='ShipMovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('geo_datetime', models.DateTimeField(blank=True, verbose_name='Дата и время определения геопозиции судна')),
                ('longitude', models.CharField(max_length=255, verbose_name='Долгота')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_history', to='ships.ship', verbose_name='Судно')),
            ],
            options={
                'verbose_name': 'История перемещения судна',
                'verbose_name_plural': 'Истории перемещения судна',
            },
        ),
    ]
