# Generated by Django 4.0.3 on 2022-03-15 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship', to=settings.AUTH_USER_MODEL, verbose_name='Владелец судна'),
        ),
    ]
